/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author DIPTO
 */
public class BestVsTeamFrame extends javax.swing.JFrame {

    /**
     * Creates new form VsFrame
     */
	public BestVsTeamFrame(){
		
	}
    public BestVsTeamFrame(String player, String goalscount) {
        initComponents(player,goalscount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String player, String goalscount) {

        jPanel1 = new javax.swing.JPanel();
        projnameLabel = new javax.swing.JLabel();
        playerphoto = new javax.swing.JLabel();
        clubphoto = new javax.swing.JLabel();
        goalLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        goal = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Player Comparision");
        setResizable(false);

        jPanel1.setLayout(null);

        projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projnameLabel.setText("Goal!!!");
        jPanel1.add(projnameLabel);
        projnameLabel.setBounds(10, 10, 110, 51);

        playerphoto.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\players\\8.jpg")); // NOI18N
        playerphoto.setText("jLabel2");
        jPanel1.add(playerphoto);
        playerphoto.setBounds(30, 80, 150, 414);

        clubphoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPTO\\workspace\\Goal\\club_logos\\2.png")); // NOI18N
        clubphoto.setText("jLabel2");
        jPanel1.add(clubphoto);
        clubphoto.setBounds(790, 170, 200, 200);

        goalLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        goalLabel.setText("Goal");
        jPanel1.add(goalLabel);
        goalLabel.setBounds(280, 270, 48, 32);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nameLabel.setText("Name");
        jPanel1.add(nameLabel);
        nameLabel.setBounds(280, 220, 70, 40);

        goal.setText(""+goalscount);
        goal.setEditable(false);
        jPanel1.add(goal);
        goal.setBounds(430, 270, 320, 30);

        name.setText(player);
        name.setEditable(false);
        jPanel1.add(name);
        name.setBounds(430, 220, 320, 30);

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        jPanel1.add(backButton);
        backButton.setBounds(660, 440, 90, 41);
        backButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				setVisible(false);
			}
		});

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\vsback.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BestVsTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BestVsTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BestVsTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BestVsTeamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BestVsTeamFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JLabel clubphoto;
    private javax.swing.JTextField goal;
    private javax.swing.JLabel goalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel playerphoto;
    private javax.swing.JLabel projnameLabel;
    // End of variables declaration                   
}
