/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

/**
 *
 * @author DIPTO
 */
public class EditInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form editInfoForm
     */
	public EditInfoFrame(){
		
	}
    public EditInfoFrame(Connection con, Statement st, int clubid) {
        initComponents(con,st,clubid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Connection con, Statement st, int clubid) {

        jPanel1 = new javax.swing.JPanel();
        editforLabel = new javax.swing.JLabel();
        editInfoNameLabel = new javax.swing.JLabel();
        stadiumLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        oldPasswordLabel = new javax.swing.JLabel();
        oldPasswordField = new javax.swing.JPasswordField();
        confirmButton = new javax.swing.JButton();
        stadiumField = new javax.swing.JTextField();
        ownerField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Edit information");
        setResizable(false);

        jPanel1.setLayout(null);

        editforLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        editforLabel.setForeground(new java.awt.Color(0, 145, 234));
        editforLabel.setText("Edit Info for");
        jPanel1.add(editforLabel);
        editforLabel.setBounds(10, 40, 250, 40);

        editInfoNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        editInfoNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        editInfoNameLabel.setText("RMA");
        jPanel1.add(editInfoNameLabel);
        editInfoNameLabel.setBounds(280, 40, 60, 34);

        stadiumLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stadiumLabel.setForeground(new java.awt.Color(255, 255, 255));
        stadiumLabel.setText("Stadium");
        jPanel1.add(stadiumLabel);
        stadiumLabel.setBounds(20, 120, 80, 25);

        ownerLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ownerLabel.setText("Owner");
        jPanel1.add(ownerLabel);
        ownerLabel.setBounds(20, 150, 70, 25);

        contactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactLabel.setText("Contact");
        jPanel1.add(contactLabel);
        contactLabel.setBounds(20, 190, 70, 25);

        newPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        newPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        newPasswordLabel.setText("New Password");
        jPanel1.add(newPasswordLabel);
        newPasswordLabel.setBounds(20, 280, 130, 25);
        jPanel1.add(newPasswordField);
        newPasswordField.setBounds(20, 320, 360, 20);

        oldPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        oldPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        oldPasswordLabel.setText("Old Password");
        jPanel1.add(oldPasswordLabel);
        oldPasswordLabel.setBounds(20, 350, 120, 25);
        jPanel1.add(oldPasswordField);
        oldPasswordField.setBounds(20, 380, 360, 20);

        confirmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        confirmButton.setText("Confirm");
        jPanel1.add(confirmButton);
        confirmButton.setBounds(20, 430, 100, 35);
        confirmButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				String newpass = newPasswordField.getText();
				String oldpass = oldPasswordField.getText();
				boolean flag = true;
				if(newpass.equals(oldpass)&&flag){
					String dmlString = "update club set stadium = '"+stadiumField.getText()+"', owner = '"+ownerField.getText()+"', contact = '"+contactArea.getText()+"', clubpassword = '"+newpass+"'";
					try {
						st.execute(dmlString);
						JOptionPane.showMessageDialog(null, "Update successful");
					} catch (SQLException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			}
		});
        
        jPanel1.add(stadiumField);
        stadiumField.setBounds(120, 120, 260, 20);
        jPanel1.add(ownerField);
        ownerField.setBounds(120, 150, 260, 20);

        contactArea.setColumns(20);
        contactArea.setRows(5);
        jScrollPane1.setViewportView(contactArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 190, 260, 96);

        backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        backButton.setText("Back");
        jPanel1.add(backButton);
        backButton.setBounds(293, 430, 80, 35);
        backButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				setVisible(false);
			}
		});

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\clubInfoEdit.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditInfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextArea contactArea;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel editInfoNameLabel;
    private javax.swing.JLabel editforLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField oldPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JTextField ownerField;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JTextField stadiumField;
    private javax.swing.JLabel stadiumLabel;
    // End of variables declaration                   
}
