/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;

/**
 *
 * @author DIPTO
 */
public class GamemgmtWindow extends javax.swing.JFrame {

    /**
     * Creates new form GamemgtWindow
     */
	public GamemgmtWindow(){
		
	}
    public GamemgmtWindow(Connection con, Statement st,String clubname) {
        initComponents(con,st,clubname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Connection con,Statement st,String clubname) {

        jPanel1 = new javax.swing.JPanel();
        projnameLabel = new javax.swing.JLabel();
        matchButton = new javax.swing.JButton();
        seasonButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Game Management");
        setResizable(false);

        jPanel1.setLayout(null);

        projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        projnameLabel.setForeground(new java.awt.Color(51, 0, 255));
        projnameLabel.setText("Goal!!!");
        jPanel1.add(projnameLabel);
        projnameLabel.setBounds(30, 30, 80, 34);

        matchButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        matchButton.setText("Match");
        jPanel1.add(matchButton);
        matchButton.setBounds(550, 100, 120, 41);
        matchButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				matchButtonActionPerformed(evt);
			}

			private void matchButtonActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				String[] opponents = null;
				String allopponentString = null;
				CallableStatement statement = null;
				System.out.println(clubname);
				try {
					//allopponentString = "{ ? = call GET_POSSIBLE_OPPONENTS(?)}";
					statement = con.prepareCall("{? = call GET_POSSIBLE_OPPONENTS(?)}");
					statement.setString(2, clubname);
					statement.registerOutParameter(1, Types.VARCHAR);
					statement.execute();
					allopponentString = statement.getString(1);
					System.out.println(allopponentString);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				opponents = allopponentString.split("/");
				for(int i=0;i<opponents.length;i++)
					System.out.println(opponents[i]);
				
				matchdataInput = new MatchInput(con,st,clubname,opponents);
				matchdataInput.setVisible(true);
			}
		});

        seasonButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        seasonButton.setText("Season");
        jPanel1.add(seasonButton);
        seasonButton.setBounds(550, 230, 120, 41);
        seasonButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				seasonButtonActionPerformed(evt);
			}
			private void seasonButtonActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				seasonwindow = new StartNewSeason(con,st);
				seasonwindow.setVisible(true);
			}
		});

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        backButton.setText("Back");
        jPanel1.add(backButton);
        backButton.setBounds(30, 390, 57, 23);
        backButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				backButtonActionPerformed(evt);
			}
			
			private void backButtonActionPerformed(ActionEvent evt){
				setVisible(false);
			}
		});

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\gamemgmt.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamemgmtWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamemgmtWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamemgmtWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamemgmtWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamemgmtWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton matchButton;
    private javax.swing.JLabel projnameLabel;
    private javax.swing.JButton seasonButton;
    private StartNewSeason seasonwindow;
    private MatchInput matchdataInput;
    // End of variables declaration                   
}
