/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author DIPTO
 */
public class HistoryForm extends javax.swing.JFrame {

    /**
     * Creates new form HistoryForm
     */
	public HistoryForm(){
		
	}
    public HistoryForm(String playername, int playerid, int goal1,int goal2,int goal3,int assist1,int assist2,int assist3,int pass1,int pass2,int pass3,int inter1,int inter2,int inter3,int save1,int save2,int save3,int value1,int value2,int value3) {
        initComponents(playername,playerid, goal1,goal2,goal3,assist1,assist2,assist3,pass1,pass2,pass3,inter1,inter2,inter3,save1,save2,save3,value1,value2,value3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String playername, int playerid, int goalcount1,int goalcount2,int goalcount3,int assistcount1,int assistcount2,int assistcount3,int passcount1,int passcount2,int passcount3,int intercount1,int intercount2,int intercount3,int savecount1,int savecount2,int savecount3,int valuecount1,int valuecount2,int valuecount3) {

        jPanel1 = new javax.swing.JPanel();
        projnameLabel = new javax.swing.JLabel();
        playernameLabel = new javax.swing.JLabel();
        playerPhoto = new javax.swing.JLabel();
        goalLabel = new javax.swing.JLabel();
        assistLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        interceptLabel = new javax.swing.JLabel();
        saveLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        previousLabel = new javax.swing.JLabel();
        currentLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        improveLabel = new javax.swing.JLabel();
        goal1 = new javax.swing.JTextField();
        goal2 = new javax.swing.JTextField();
        goal3 = new javax.swing.JTextField();
        assist1 = new javax.swing.JTextField();
        assist2 = new javax.swing.JTextField();
        assist3 = new javax.swing.JTextField();
        pass1 = new javax.swing.JTextField();
        pass2 = new javax.swing.JTextField();
        pass3 = new javax.swing.JTextField();
        intercept1 = new javax.swing.JTextField();
        intercept2 = new javax.swing.JTextField();
        intercept3 = new javax.swing.JTextField();
        save1 = new javax.swing.JTextField();
        save2 = new javax.swing.JTextField();
        save3 = new javax.swing.JTextField();
        value1 = new javax.swing.JTextField();
        value2 = new javax.swing.JTextField();
        value3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setLayout(null);

        projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projnameLabel.setText("Goal!!!");
        jPanel1.add(projnameLabel);
        projnameLabel.setBounds(20, 30, 110, 51);

        playernameLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        playernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        playernameLabel.setText(playername+" History");
        jPanel1.add(playernameLabel);
        playernameLabel.setBounds(20, 90, 140, 22);

        playerPhoto.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\players\\"+playerid+".jpg")); // NOI18N
        jPanel1.add(playerPhoto);
        playerPhoto.setBounds(20, 120, 150, 414);

        goalLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        goalLabel.setText("Goal");
        jPanel1.add(goalLabel);
        goalLabel.setBounds(190, 150, 140, 29);

        assistLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        assistLabel.setText("Assist");
        jPanel1.add(assistLabel);
        assistLabel.setBounds(190, 200, 140, 29);

        passLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        passLabel.setText("Pass");
        jPanel1.add(passLabel);
        passLabel.setBounds(190, 250, 140, 29);

        interceptLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        interceptLabel.setText("Intercept");
        jPanel1.add(interceptLabel);
        interceptLabel.setBounds(190, 300, 140, 29);

        saveLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        saveLabel.setText("Save");
        jPanel1.add(saveLabel);
        saveLabel.setBounds(190, 350, 140, 29);

        valueLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        valueLabel.setText("Market Value");
        jPanel1.add(valueLabel);
        valueLabel.setBounds(190, 400, 140, 29);

        previousLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        previousLabel.setText("Previous");
        jPanel1.add(previousLabel);
        previousLabel.setBounds(360, 100, 100, 40);

        currentLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        currentLabel.setText("Current");
        jPanel1.add(currentLabel);
        currentLabel.setBounds(540, 100, 90, 40);

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        jPanel1.add(backButton);
        backButton.setBounds(833, 490, 90, 41);
        backButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				setVisible(false);
			}
		});

        improveLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        improveLabel.setText("Effective improve");
        jPanel1.add(improveLabel);
        improveLabel.setBounds(690, 100, 190, 40);

        goal1.setText(""+goalcount1);
        goal1.setEditable(false);
        goal1.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(goal1);
        goal1.setBounds(360, 150, 90, 25);

        goal2.setText(""+goalcount2);
        goal2.setEditable(false);
        goal2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(goal2);
        goal2.setBounds(540, 150, 90, 25);

        goal3.setText(""+goalcount3);
        goal3.setEditable(false);
        goal3.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(goal3);
        goal3.setBounds(730, 150, 90, 25);

        assist1.setText(""+assistcount1);
        assist1.setEditable(false);
        assist1.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(assist1);
        assist1.setBounds(360, 200, 90, 25);

        assist2.setText(""+assistcount2);
        assist2.setEditable(false);
        assist2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(assist2);
        assist2.setBounds(540, 200, 90, 25);

        assist3.setText(""+assistcount3);
        assist3.setEditable(false);
        assist3.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(assist3);
        assist3.setBounds(730, 200, 90, 25);

        pass1.setText(""+passcount1);
        pass1.setEditable(false);
        pass1.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(pass1);
        pass1.setBounds(360, 250, 90, 25);

        pass2.setText(""+passcount2);
        pass2.setEditable(false);
        pass2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(pass2);
        pass2.setBounds(540, 250, 90, 25);

        pass3.setText(""+passcount3);
        pass3.setEditable(false);
        pass3.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(pass3);
        pass3.setBounds(730, 250, 90, 25);

        intercept1.setText(""+intercount1);
        intercept1.setEditable(false);
        intercept1.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(intercept1);
        intercept1.setBounds(360, 300, 90, 25);

        intercept2.setText(""+intercount2);
        intercept2.setEditable(false);
        intercept2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(intercept2);
        intercept2.setBounds(540, 300, 90, 25);

        intercept3.setText(""+intercount3);
        intercept3.setEditable(false);
        intercept3.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(intercept3);
        intercept3.setBounds(730, 300, 90, 25);

        save1.setText(""+savecount1);
        save1.setEditable(false);
        save1.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(save1);
        save1.setBounds(360, 350, 90, 25);

        save2.setText(""+savecount2);
        save2.setEditable(false);
        save2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(save2);
        save2.setBounds(540, 350, 90, 25);

        save3.setText(""+savecount3);
        save3.setEditable(false);
        save3.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(save3);
        save3.setBounds(730, 350, 90, 25);

        value1.setText(""+valuecount1);
        value1.setEditable(false);
        value1.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(value1);
        value1.setBounds(360, 400, 90, 25);

        value2.setText(""+valuecount2);
        value2.setEditable(false);
        value2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(value2);
        value2.setBounds(540, 400, 90, 25);

        value3.setText(""+valuecount3);
        value3.setEditable(false);
        value3.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        jPanel1.add(value3);
        value3.setBounds(730, 400, 90, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\playerHistory.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 4, 960, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField assist1;
    private javax.swing.JTextField assist2;
    private javax.swing.JTextField assist3;
    private javax.swing.JLabel assistLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel currentLabel;
    private javax.swing.JTextField goal1;
    private javax.swing.JTextField goal2;
    private javax.swing.JTextField goal3;
    private javax.swing.JLabel goalLabel;
    private javax.swing.JLabel improveLabel;
    private javax.swing.JTextField intercept1;
    private javax.swing.JTextField intercept2;
    private javax.swing.JTextField intercept3;
    private javax.swing.JLabel interceptLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pass1;
    private javax.swing.JTextField pass2;
    private javax.swing.JTextField pass3;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel playerPhoto;
    private javax.swing.JLabel playernameLabel;
    private javax.swing.JLabel previousLabel;
    private javax.swing.JLabel projnameLabel;
    private javax.swing.JTextField save1;
    private javax.swing.JTextField save2;
    private javax.swing.JTextField save3;
    private javax.swing.JLabel saveLabel;
    private javax.swing.JTextField value1;
    private javax.swing.JTextField value2;
    private javax.swing.JTextField value3;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration                   
}
