/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JButton;
import javax.swing.JOptionPane;

import server.ui.JDBC_connector;

/**
 *
 * @author DIPTO
 */
public class LoginInterface extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
	public LoginInterface(){
		
	}
    public LoginInterface(Connection con, Statement st) {
        initComponents(con,st);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Connection con,Statement st) {

        jPanel1 = new javax.swing.JPanel();
        projectNameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        clubUsernameField = new javax.swing.JTextField();
        clubPasswordLabel = new javax.swing.JLabel();
        clubPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        guestButton = new javax.swing.JButton();
        signupPromptLabel = new javax.swing.JLabel();
        signupButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        projectNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projectNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectNameLabel.setText("GOAL!!!");
        jPanel1.add(projectNameLabel);
        projectNameLabel.setBounds(40, 40, 140, 40);

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 230, 118));
        usernameLabel.setText("Club Username");
        jPanel1.add(usernameLabel);
        usernameLabel.setBounds(40, 100, 170, 32);

        clubUsernameField.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(clubUsernameField);
        clubUsernameField.setBounds(40, 150, 350, 30);

        clubPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clubPasswordLabel.setForeground(new java.awt.Color(0, 230, 118));
        clubPasswordLabel.setText("Club Password");
        jPanel1.add(clubPasswordLabel);
        clubPasswordLabel.setBounds(40, 210, 160, 32);

        clubPasswordField.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jPanel1.add(clubPasswordField);
        clubPasswordField.setBounds(40, 260, 350, 30);

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(26, 35, 126));
        loginButton.setText("Login");
        jPanel1.add(loginButton);
        loginButton.setBounds(40, 320, 120, 41);
        loginButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				loginButtonActionPerformed(evt);
			}
			
			private void loginButtonActionPerformed(ActionEvent evt){
				ResultSet rs;
				String accountchecksql = "select count(*) from club where clubusername = '"+clubUsernameField.getText() +"' and clubpassword = '"+clubPasswordField.getText()+"'";
				int flag=0;
				try {
	    			rs = st.executeQuery(accountchecksql);
	    			while (rs.next()) {				
	    				flag = rs.getInt(1);
	    			}
	    			if(flag==1){
	    				System.out.println("Match found");
	    				String getclubidString = "select clubid from club where clubusername = '"+clubUsernameField.getText()+"'";
	    				rs = st.executeQuery(getclubidString);
	    				int clubid = 0;
	    				while(rs.next()){
	    					clubid = rs.getInt(1);
	    				}
	    				teaminfoframe = new Teamframe(con,st,clubUsernameField.getText(),clubid);
	    				teaminfoframe.setVisible(true);
	    				setVisible(false);
	    			}
	    			else {
	    				JOptionPane.showMessageDialog(null, "Wrong Login credentials");
					}
	    		} catch (SQLException e) {
	    			// TODO Auto-generated catch block
	    			e.printStackTrace();
	    		}
			}
		});

        signupPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signupPromptLabel.setForeground(new java.awt.Color(255, 255, 255));
        signupPromptLabel.setText("Don't have an account?");
        jPanel1.add(signupPromptLabel);
        signupPromptLabel.setBounds(40, 480, 210, 25);
        signupPromptLabel.setVisible(false);
        signupButton.setVisible(false);
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }

			private void signupButtonActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
	    		setVisible(false);
			}
        });
        
//        private void signupButtonActionPerformed(ActionEvent evt) {
//    		signupform = new Signup();
//    		signupform.setVisible(true);
//    		setVisible(false);
//    	}

        signupButton.setText("Sign up");
        jPanel1.add(signupButton);
        signupButton.setBounds(260, 480, 70, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("photo_lib/login.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPasswordField clubPasswordField;
    public String pass;
    private javax.swing.JLabel clubPasswordLabel;
    private javax.swing.JTextField clubUsernameField;
    public String user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton guestButton;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel signupPromptLabel;
    private javax.swing.JLabel usernameLabel;
    private Teamframe teaminfoframe;
    // End of variables declaration                   
}
