/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author DIPTO
 */
public class PlayerVsFrame extends javax.swing.JFrame {

	/**
	 * Creates new form VsFrame
	 */
	public PlayerVsFrame() {

	}

	public PlayerVsFrame(String player1, String player2, String pos1,
			String pos2, int match1, int match2, int goal1, int goal2,
			int assist1, int assist2, double pass1, double pass2, int save1,
			int save2, Connection con, Statement st) {
		initComponents(player1, player2, pos1, pos2, match1, match2, goal1,
				goal2, assist1, assist2, pass1, pass2, save1, save2, con, st);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(String playername1, String playername2,
			String posstr1, String posstr2, int matchcount1, int matchcount2,
			int goalcount1, int goalcount2, int assistcount1, int assistcount2,
			double passcount1, double passcount2, int savecount1,
			int savecount2, Connection con, Statement st) {

		jPanel1 = new javax.swing.JPanel();
		projnameLabel = new javax.swing.JLabel();
		playerphoto1 = new javax.swing.JLabel();
		playerphoto2 = new javax.swing.JLabel();
		player1 = new javax.swing.JLabel();
		player2 = new javax.swing.JLabel();
		goalLabel = new javax.swing.JLabel();
		assistLabel = new javax.swing.JLabel();
		passAccLabel = new javax.swing.JLabel();
		saveLabel = new javax.swing.JLabel();
		goal1 = new javax.swing.JTextField();
		goal2 = new javax.swing.JTextField();
		assist1 = new javax.swing.JTextField();
		assist2 = new javax.swing.JTextField();
		pass1 = new javax.swing.JTextField();
		pass2 = new javax.swing.JTextField();
		save1 = new javax.swing.JTextField();
		save2 = new javax.swing.JTextField();
		backButton = new javax.swing.JButton();
		matchPlayedLabel = new javax.swing.JLabel();
		match1 = new javax.swing.JTextField();
		match2 = new javax.swing.JTextField();
		posLabel = new javax.swing.JLabel();
		pos1 = new javax.swing.JTextField();
		pos2 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();

		String label1sql = "select playerid from player where playername = '"
				+ playername1 + "'";
		String label1find = null;
		try {
			ResultSet rs = st.executeQuery(label1sql);
			while (rs.next()) {
				label1find = rs.getString(1);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		String label2sql = "select playerid from player where playername = '"
				+ playername2 + "'";
		String label2find = null;
		try {
			ResultSet rs = st.executeQuery(label2sql);
			while (rs.next()) {
				label2find = rs.getString(1);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
		setTitle("Player Comparision");
		setResizable(false);

		jPanel1.setLayout(null);

		projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
		projnameLabel.setText("Goal!!!");
		jPanel1.add(projnameLabel);
		projnameLabel.setBounds(10, 10, 110, 51);

		playerphoto1.setIcon(new javax.swing.ImageIcon(
				"E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\players\\"
						+ label1find + ".jpg")); // NOI18N
		playerphoto1.setText("");
		jPanel1.add(playerphoto1);
		playerphoto1.setBounds(30, 80, 150, 414);

		playerphoto2.setIcon(new javax.swing.ImageIcon(
				"E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\players\\"
						+ label2find + ".jpg")); // NOI18N
		playerphoto2.setText("jLabel2");
		jPanel1.add(playerphoto2);
		playerphoto2.setBounds(840, 80, 150, 414);

		player1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		player1.setText(playername1);
		jPanel1.add(player1);
		player1.setBounds(250, 80, 160, 32);

		player2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		player2.setText(playername2);
		jPanel1.add(player2);
		player2.setBounds(620, 80, 170, 32);

		goalLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		goalLabel.setText("Goal");
		jPanel1.add(goalLabel);
		goalLabel.setBounds(470, 240, 48, 32);

		assistLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		assistLabel.setText("Assist");
		jPanel1.add(assistLabel);
		assistLabel.setBounds(470, 290, 70, 40);

		passAccLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		passAccLabel.setText("Pass Acuracy");
		jPanel1.add(passAccLabel);
		passAccLabel.setBounds(440, 350, 140, 50);

		saveLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		saveLabel.setText("Save");
		jPanel1.add(saveLabel);
		saveLabel.setBounds(480, 420, 50, 50);

		goal1.setText("" + goalcount1);
		goal1.setEditable(false);
		jPanel1.add(goal1);
		goal1.setBounds(250, 240, 120, 30);

		goal2.setText("" + goalcount2);
		goal2.setEditable(false);
		jPanel1.add(goal2);
		goal2.setBounds(620, 240, 130, 30);

		assist1.setText("" + assistcount1);
		assist1.setEditable(false);
		jPanel1.add(assist1);
		assist1.setBounds(250, 300, 120, 30);

		assist2.setText("" + assistcount2);
		assist2.setEditable(false);
		jPanel1.add(assist2);
		assist2.setBounds(620, 300, 130, 30);

		pass1.setText("" + passcount1);
		pass1.setEditable(false);
		jPanel1.add(pass1);
		pass1.setBounds(250, 360, 120, 30);

		pass2.setText("" + passcount2);
		pass2.setEditable(false);
		jPanel1.add(pass2);
		pass2.setBounds(620, 360, 130, 30);

		save1.setText("" + savecount1);
		save1.setEditable(false);
		jPanel1.add(save1);
		save1.setBounds(250, 430, 120, 30);

		save2.setText("" + savecount2);
		save2.setEditable(false);
		jPanel1.add(save2);
		save2.setBounds(620, 430, 130, 30);

		backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		backButton.setText("Back");
		jPanel1.add(backButton);
		backButton.setBounds(450, 490, 90, 41);
		backButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				setVisible(false);
			}
		});

		matchPlayedLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		matchPlayedLabel.setText("Matches");
		jPanel1.add(matchPlayedLabel);
		matchPlayedLabel.setBounds(450, 130, 90, 32);

		match1.setText("" + matchcount1);
		match1.setEditable(false);
		match1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		jPanel1.add(match1);
		match1.setBounds(250, 140, 120, 30);

		match2.setText("" + matchcount2);
		match2.setEditable(false);
		match2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		jPanel1.add(match2);
		match2.setBounds(620, 140, 130, 30);

		posLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		posLabel.setText("Position");
		jPanel1.add(posLabel);
		posLabel.setBounds(450, 180, 90, 32);

		pos1.setText(posstr1);
		pos1.setEditable(false);
		pos1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		jPanel1.add(pos1);
		pos1.setBounds(250, 190, 120, 30);

		pos2.setText(posstr2);
		pos2.setEditable(false);
		pos2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
		jPanel1.add(pos2);
		pos2.setBounds(620, 188, 130, 30);

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\vsback.jpg")); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 1024, 540);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PlayerVsFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PlayerVsFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PlayerVsFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PlayerVsFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PlayerVsFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField assist1;
	private javax.swing.JTextField assist2;
	private javax.swing.JLabel assistLabel;
	private javax.swing.JButton backButton;
	private javax.swing.JTextField goal1;
	private javax.swing.JTextField goal2;
	private javax.swing.JLabel goalLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField match1;
	private javax.swing.JTextField match2;
	private javax.swing.JLabel matchPlayedLabel;
	private javax.swing.JTextField pass1;
	private javax.swing.JTextField pass2;
	private javax.swing.JLabel passAccLabel;
	private javax.swing.JLabel player1;
	private javax.swing.JLabel player2;
	private javax.swing.JLabel playerphoto1;
	private javax.swing.JLabel playerphoto2;
	private javax.swing.JTextField pos1;
	private javax.swing.JTextField pos2;
	private javax.swing.JLabel posLabel;
	private javax.swing.JLabel projnameLabel;
	private javax.swing.JTextField save1;
	private javax.swing.JTextField save2;
	private javax.swing.JLabel saveLabel;
	// End of variables declaration
}
