/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author DIPTO
 */
public class Teamframe extends javax.swing.JFrame {

    /**
     * Creates new form teamInfo
     */
    public Teamframe(Connection con, Statement st, String clubusrname, int clubid) {
        initComponents(con,st,clubusrname,clubid);
    }
    public Teamframe() {
		// TODO Auto-generated constructor stub
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Connection con,Statement st,String clubusrname,int clubid) {

        jPanel1 = new javax.swing.JPanel();
        projnameLabel = new javax.swing.JLabel();
        teamLogo = new javax.swing.JLabel();
        teamManageButton = new javax.swing.JButton();
        matchButton = new javax.swing.JButton();
        queryButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Team Frame");
        setResizable(false);

        jPanel1.setLayout(null);

        projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        projnameLabel.setText("Goal!!!");
        jPanel1.add(projnameLabel);
        projnameLabel.setBounds(30, 20, 110, 60);

        teamLogo.setIcon(new javax.swing.ImageIcon("club_logos/"+clubid+".png")); // NOI18N
        jPanel1.add(teamLogo);
        teamLogo.setBounds(30, 120, 200, 200);

        teamManageButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        teamManageButton.setForeground(new java.awt.Color(0, 204, 204));
        teamManageButton.setText("Team management");
        jPanel1.add(teamManageButton);
        teamManageButton.setBounds(420, 110, 260, 40);
        teamManageButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				teamManageButtonActionPerformed(evt);
			}

			private void teamManageButtonActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				teammgmt = new TeammgmtFrame(con,st,clubid);
				teammgmt.setVisible(true);
			}
		});

        matchButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        matchButton.setForeground(new java.awt.Color(0, 204, 204));
        matchButton.setText("Games");
        matchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(matchButton);
        matchButton.setBounds(420, 190, 260, 41);
        matchButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				matchButtonActionPerformed(evt);
			}
			private void matchButtonActionPerformed(ActionEvent evt){
				String clubname = null;
				try {
					ResultSet rs = st.executeQuery("select clubname from club WHERE clubusername='"+clubusrname+"'");
					while (rs.next()) {
						clubname = rs.getString(1);
					}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				gamewindow = new GamemgmtWindow(con,st,clubname);
				gamewindow.setVisible(true);
			}
		});

        queryButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        queryButton.setForeground(new java.awt.Color(0, 204, 204));
        queryButton.setText("Query");
        jPanel1.add(queryButton);
        queryButton.setBounds(420, 280, 260, 41);
        queryButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				queryButtonActionPerformed(evt);
			}
			
			private void queryButtonActionPerformed(ActionEvent evt){
		    	query = new QueryForm(con,st);
		    	query.setVisible(true);
		    }
		});

        jLabel1.setIcon(new javax.swing.ImageIcon("photo_lib/teamInfo.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void matchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teamframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teamframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teamframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teamframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teamframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton matchButton;
    private javax.swing.JLabel projnameLabel;
    private javax.swing.JButton queryButton;
    private javax.swing.JLabel teamLogo;
    private javax.swing.JButton teamManageButton;
    private QueryForm query;
    private GamemgmtWindow gamewindow;
    private TeammgmtFrame teammgmt;
    // End of variables declaration                   
}
