/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author DIPTO
 */
public class TeammgmtFrame extends javax.swing.JFrame {

    /**
     * Creates new form TeammgmtFrame
     */
	public TeammgmtFrame(){
		
	}
    public TeammgmtFrame(Connection con,Statement st, int clubid) {
        initComponents(con,st,clubid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Connection con,Statement st,int clubid) {

        jPanel1 = new javax.swing.JPanel();
        projnameLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        playerHistoryButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setLayout(null);

        projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projnameLabel.setText("Goal!!!");
        projnameLabel.setToolTipText("");
        jPanel1.add(projnameLabel);
        projnameLabel.setBounds(20, 20, 100, 51);

        editButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        editButton.setText("Edit Team info");
        jPanel1.add(editButton);
        editButton.setBounds(20, 120, 190, 41);
        editButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				editinfo = new EditInfoFrame(con,st,clubid);
				editinfo.setVisible(true);
			}
		});
        
        String playerscountsql = "select count(playername) from player where currentclubid = "+clubid;
		int count = 0;
		try {
			ResultSet rs = st.executeQuery(playerscountsql);
			while(rs.next()){
				count = rs.getInt(1);
			}
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
		String[] allplayers = new String[count];
		String playerssql = "select playername from player where currentclubid = "+clubid;
		try {
			ResultSet rs = st.executeQuery(playerssql);
			int i=0;
			while(rs.next()){
				allplayers[i] = rs.getString(1);
				i++;
			}
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

        playerHistoryButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        playerHistoryButton.setText("Player History");
        jPanel1.add(playerHistoryButton);
        playerHistoryButton.setBounds(20, 210, 190, 41);
        playerHistoryButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				historySelectForm = new HistorySelectForm(con, st, allplayers);
				historySelectForm.setVisible(true);
			}
		});

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        jPanel1.add(backButton);
        backButton.setBounds(660, 440, 81, 41);
        backButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				setVisible(false);
			}
		});

        transferButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transferButton.setText("Transfer");
        jPanel1.add(transferButton);
        transferButton.setBounds(20, 300, 190, 41);
        transferButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				transferSearch = new TransferSearchFrame(con,st,clubid);
				transferSearch.setVisible(true);
			}
		});

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\TeamManage.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeammgmtFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeammgmtFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeammgmtFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeammgmtFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeammgmtFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playerHistoryButton;
    private javax.swing.JLabel projnameLabel;
    private javax.swing.JButton transferButton;
    private EditInfoFrame editinfo;
    private HistorySelectForm historySelectForm;
    private TransferSearchFrame transferSearch;
    // End of variables declaration                   
}
