/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

/**
 *
 * @author DIPTO
 */
public class TransferFrame extends javax.swing.JFrame {

	/**
	 * Creates new form TransferSelectFrame
	 */
	public TransferFrame(){
		
	}
	public TransferFrame(String[] tranplayer, String clubname,Connection con, Statement st) {
		initComponents(tranplayer,clubname,con,st);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(String[] tranplayer, String clubname,Connection con, Statement st) {

		jPanel1 = new javax.swing.JPanel();
		projNameLabel = new javax.swing.JLabel();
		targetedPlayersList = new javax.swing.JComboBox();
		buyButton = new javax.swing.JButton();
		backButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

		jPanel1.setLayout(null);

		projNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
		projNameLabel.setText("Goal!!!");
		jPanel1.add(projNameLabel);
		projNameLabel.setBounds(20, 20, 110, 51);

		targetedPlayersList.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
		targetedPlayersList.setModel(new javax.swing.DefaultComboBoxModel(tranplayer));
		jPanel1.add(targetedPlayersList);
		targetedPlayersList.setBounds(500, 90, 500, 35);

		buyButton.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
		buyButton.setText("Buy");
		buyButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buyButtonActionPerformed(evt);
			}
			
			private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {
				// TODO add your handling code here:
				CallableStatement buyStatement = null;
				String playername = (String)targetedPlayersList.getSelectedItem();
				try {
					buyStatement = con.prepareCall("{call TRANSFER(?,?)}");
					buyStatement.setString(1, playername);
					buyStatement.setString(2, clubname);
					buyStatement.execute();
					buyButton.setEnabled(false);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		jPanel1.add(buyButton);
		buyButton.setBounds(903, 420, 90, 37);

		backButton.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
		backButton.setText("Back");
		jPanel1.add(backButton);
		backButton.setBounds(30, 420, 83, 40);
		backButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				setVisible(false);
			}
		});

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\transferSelect.jpg")); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 1024, 500);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TransferFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TransferFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TransferFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TransferFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TransferFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton backButton;
	private javax.swing.JButton buyButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel projNameLabel;
	private javax.swing.JComboBox targetedPlayersList;
	// End of variables declaration
}
