/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;

/**
 *
 * @author DIPTO
 */
public class TransferResultFrame extends javax.swing.JFrame {

	/**
	 * Creates new form TransferResultFrame
	 */
	public TransferResultFrame(){
		
	}
	public TransferResultFrame(Object[][] alldata,String clubname,Connection con, Statement st) {
		initComponents(alldata,clubname,con,st);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Object[][] alldata,String clubname,Connection con, Statement st) {

        jPanel1 = new javax.swing.JPanel();
        projnameLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Transfer Search Result");
        setResizable(false);

        jPanel1.setLayout(null);

        projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projnameLabel.setText("Goal!!!");
        jPanel1.add(projnameLabel);
        projnameLabel.setBounds(20, 20, 100, 51);

        resultLabel.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        resultLabel.setText("These players satisfy your search criteria");
        jPanel1.add(resultLabel);
        resultLabel.setBounds(160, 70, 440, 29);
        
        String[] colheads = {
                "Player name", "Age", "Overall", "Market Value"
            };

        searchResTable.setModel(new javax.swing.table.DefaultTableModel(alldata,colheads));
        jScrollPane1.setViewportView(searchResTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 452, 190);

        backButton.setText("Back");
        jPanel1.add(backButton);
        backButton.setBounds(680, 360, 55, 23);
        backButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				setVisible(false);
			}
		});

        transferButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transferButton.setText("Transfer Activity");
        jPanel1.add(transferButton);
        transferButton.setBounds(560, 210, 170, 31);
        transferButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				String[] tranplayer = new String[10];
				for(int i=0; i<10; i++){
					tranplayer[i]=  (String)alldata[i][0]; 
				}
				
				for(int i=0; i<10; i++){
					System.out.println(tranplayer[i]); 
				}
				
				buyFrame = new TransferFrame(tranplayer,clubname,con,st);
				buyFrame.setVisible(true);
			}
		});

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\transferRes.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					TransferResultFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					TransferResultFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					TransferResultFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					TransferResultFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TransferResultFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton backButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel projnameLabel;
	private javax.swing.JLabel resultLabel;
	private javax.swing.JTable searchResTable;
	private javax.swing.JButton transferButton;
	private TransferFrame buyFrame;
	// End of variables declaration
}
