/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client.ui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.omg.CORBA.OBJ_ADAPTER;

/**
 *
 * @author DIPTO
 */
public class TransferSearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form TransferSearchFrame
     */
	public TransferSearchFrame(){
		
	}
    public TransferSearchFrame(Connection con,Statement st, int clubid) {
        initComponents(con,st,clubid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Connection con, Statement st, int clubid) {

        jPanel1 = new javax.swing.JPanel();
        projnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        minLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        positionList = new javax.swing.JComboBox();
        age1 = new javax.swing.JTextField();
        age2 = new javax.swing.JTextField();
        value1 = new javax.swing.JTextField();
        value2 = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Transfer Search");
        setResizable(false);

        jPanel1.setLayout(null);

        projnameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projnameLabel.setText("Goal!!!");
        jPanel1.add(projnameLabel);
        projnameLabel.setBounds(30, 30, 110, 51);

        ageLabel.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        ageLabel.setText("Age");
        jPanel1.add(ageLabel);
        ageLabel.setBounds(30, 160, 210, 43);

        valueLabel.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        valueLabel.setText("Market value");
        jPanel1.add(valueLabel);
        valueLabel.setBounds(30, 230, 210, 43);

        minLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        minLabel.setText("Minimum");
        jPanel1.add(minLabel);
        minLabel.setBounds(290, 130, 80, 22);

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel3.setText("Maximum");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(470, 130, 80, 22);

        positionLabel.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        positionLabel.setText("Position");
        jPanel1.add(positionLabel);
        positionLabel.setBounds(750, 100, 130, 50);

        positionList.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        positionList.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"ATT", "MID", "DEF", "GK" }));
        jPanel1.add(positionList);
        positionList.setBounds(710, 160, 210, 35);

        age1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        age1.setText("10");
        jPanel1.add(age1);
        age1.setBounds(270, 160, 120, 35);

        age2.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        age2.setText("50");
        jPanel1.add(age2);
        age2.setBounds(450, 160, 120, 35);

        value1.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        value1.setText("30000");
        jPanel1.add(value1);
        value1.setBounds(270, 230, 120, 35);

        value2.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        value2.setText("10000000");
        jPanel1.add(value2);
        value2.setBounds(450, 230, 120, 35);

        searchButton.setFont(new java.awt.Font("Cambria Math", 0, 48)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
            
            private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
                // TODO add your handling code here:
            	String transfersearchstr = "select * from (select p.playername,round( (sysdate-p.playerdob)/365), getoverall(p.playername) OVERALL, s.marketval from seasonstat s join player p on (p.playerid=s.playerid) where ("+age1.getText()+"<=(sysdate-p.playerdob)/365 and ((sysdate-p.playerdob)/365)<="+age2.getText()+")  and ("+value1.getText()+"<= s.marketval and s.marketval<="+value2.getText()+")  and p.preferpos='"+(String)positionList.getSelectedItem()+"' and s.seasonid=(select seasonid from season where sysdate>=startdate and sysdate<=enddate) order by overall desc, s.marketval desc) where rownum<=10";
            	Object[][] alldata = new Object[10][4];
            	try {
					ResultSet rs = st.executeQuery(transfersearchstr);
					int i=0;
					while(rs.next()){
						alldata[i][0] = rs.getString(1);
						alldata[i][1] = rs.getInt(2);
						alldata[i][2] = rs.getDouble(3);
						alldata[i][3] = rs.getDouble(4);
						i++;
					}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            	
            	String clubnamesql = "select clubname from club where clubid="+clubid;
            	String clubname = null;
            	try {
					ResultSet rs = st.executeQuery(clubnamesql);
					while(rs.next()){
						clubname = rs.getString(1);
					}
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            	            	
            	transferResult = new TransferResultFrame(alldata,clubname,con,st);
            	transferResult.setVisible(true);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(400, 370, 180, 65);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\BUET\\Level 3 Term 1\\CSE 304\\project\\manyplayers.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferSearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField age1;
    private javax.swing.JTextField age2;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minLabel;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JComboBox positionList;
    private javax.swing.JLabel projnameLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField value1;
    private javax.swing.JTextField value2;
    private javax.swing.JLabel valueLabel;
    private TransferResultFrame transferResult;
    // End of variables declaration                   
}
