/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package server.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;

import client.ui.GuestProceed;
import client.ui.LoginInterface;
import server.ui.JDBC_connector;
/**
 *
 * @author DIPTO
 */
public class ServerInterface extends javax.swing.JFrame {

    /**
     * Creates new form servercon
     */
    public ServerInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        projNameLabel = new javax.swing.JLabel();
        serverSideLabel = new javax.swing.JLabel();
        conNameLabel = new javax.swing.JLabel();
        conNameField = new javax.swing.JTextField();
        conTypeLabel = new javax.swing.JLabel();
        conTypeField = new javax.swing.JTextField();
        hostNameLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        serviceNameLabel = new javax.swing.JLabel();
        hostField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        serviceNameField = new javax.swing.JTextField();
        testConnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        conStatusArea = new javax.swing.JTextArea();
        userNameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        proceedButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        buetLogo = new javax.swing.JLabel();
        buetLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server UI");
        setResizable(false);

        jPanel1.setLayout(null);

        projNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        projNameLabel.setForeground(new java.awt.Color(26, 35, 126));
        projNameLabel.setText("GOAL!!!");
        jPanel1.add(projNameLabel);
        projNameLabel.setBounds(20, 10, 126, 51);

        serverSideLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        serverSideLabel.setForeground(new java.awt.Color(57, 73, 171));
        serverSideLabel.setText("Server Side Interface");
        jPanel1.add(serverSideLabel);
        serverSideLabel.setBounds(20, 50, 180, 25);

        conNameLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        conNameLabel.setForeground(new java.awt.Color(48, 79, 254));
        conNameLabel.setText("Connection Name: ");
        jPanel1.add(conNameLabel);
        conNameLabel.setBounds(20, 110, 150, 22);

        conNameField.setForeground(new java.awt.Color(101, 31, 255));
        conNameField.setText("FootballTest");
        jPanel1.add(conNameField);
        conNameField.setBounds(180, 110, 310, 20);

        conTypeLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        conTypeLabel.setForeground(new java.awt.Color(48, 79, 254));
        conTypeLabel.setText("Connection Type: ");
        jPanel1.add(conTypeLabel);
        conTypeLabel.setBounds(20, 150, 150, 22);

        conTypeField.setForeground(new java.awt.Color(101, 31, 255));
        conTypeField.setText("Basic");
        jPanel1.add(conTypeField);
        conTypeField.setBounds(180, 150, 310, 20);

        hostNameLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        hostNameLabel.setForeground(new java.awt.Color(48, 79, 254));
        hostNameLabel.setText("Host/IP Address: ");
        jPanel1.add(hostNameLabel);
        hostNameLabel.setBounds(20, 190, 150, 22);

        portLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        portLabel.setForeground(new java.awt.Color(48, 79, 254));
        portLabel.setText("Port:");
        jPanel1.add(portLabel);
        portLabel.setBounds(20, 230, 150, 22);

        serviceNameLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        serviceNameLabel.setForeground(new java.awt.Color(48, 79, 254));
        serviceNameLabel.setText("Service Name: ");
        jPanel1.add(serviceNameLabel);
        serviceNameLabel.setBounds(20, 270, 140, 22);

        hostField.setForeground(new java.awt.Color(101, 31, 255));
        hostField.setText("localHost");
        jPanel1.add(hostField);
        hostField.setBounds(180, 190, 310, 20);

        portField.setForeground(new java.awt.Color(101, 31, 255));
        portField.setText("1521");
        jPanel1.add(portField);
        portField.setBounds(180, 230, 310, 20);

        serviceNameField.setForeground(new java.awt.Color(101, 31, 255));
        serviceNameField.setText("orcl");
        jPanel1.add(serviceNameField);
        serviceNameField.setBounds(180, 270, 310, 20);

        testConnButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        testConnButton.setForeground(new java.awt.Color(13, 71, 161));
        testConnButton.setText("Test Connection");
        jPanel1.add(testConnButton);
        testConnButton.setBounds(20, 340, 160, 40);
        testConnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testConnButtonActionPerformed(evt);
            }
        });

        conStatusArea.setColumns(20);
        conStatusArea.setRows(5);
        conStatusArea.setEditable(false);
        jScrollPane1.setViewportView(conStatusArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 340, 300, 140);

        userNameLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(0, 145, 234));
        userNameLabel.setText("Username");
        jPanel1.add(userNameLabel);
        userNameLabel.setBounds(560, 110, 79, 22);

        usernameField.setForeground(new java.awt.Color(0, 145, 234));
        usernameField.setText("football");
        jPanel1.add(usernameField);
        usernameField.setBounds(560, 150, 320, 20);

        passwordLabel.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 145, 234));
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(560, 190, 80, 22);

        passwordField.setForeground(new java.awt.Color(0, 145, 234));
        passwordField.setText("pes");
        jPanel1.add(passwordField);
        passwordField.setBounds(560, 230, 320, 20);

        proceedButton.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        proceedButton.setForeground(new java.awt.Color(98, 0, 234));
        proceedButton.setText("Proceed");
        proceedButton.setEnabled(false);
        jPanel1.add(proceedButton);
        proceedButton.setBounds(560, 290, 110, 30);
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(98, 0, 234));
        closeButton.setText("Close");
        jPanel1.add(closeButton);
        closeButton.setBounds(773, 290, 100, 30);
        closeButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				setVisible(false);
				System.exit(1);
			}
		});

        buetLogo.setIcon(new javax.swing.ImageIcon("photo_lib/BuetLogo.png")); // NOI18N
        jPanel1.add(buetLogo);
        buetLogo.setBounds(820, 400, 52, 52);

        buetLabel.setForeground(new java.awt.Color(153, 0, 0));
        buetLabel.setText("A project under CSE304 course, CSE, BUET");
        jPanel1.add(buetLabel);
        buetLabel.setBounds(670, 460, 210, 14);

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("photo_lib/startpage.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    
    private void testConnButtonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	host = hostField.getText();
		port = portField.getText();
		serviceName = serviceNameField.getText();
		user = usernameField.getText();
		pass = passwordField.getText();
		try {
			JDBC_connector.connect(host, port, serviceName, user, pass);
			conStatusArea.setForeground(new java.awt.Color(0, 255, 0));
			conStatusArea.setText("Success");
			proceedButton.setEnabled(true);
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			conStatusArea.setForeground(new java.awt.Color(255, 0, 0));
			conStatusArea.setText("Failure");
			e.printStackTrace();
		}
	}
    
    public static void setConnStatusField(boolean flag) {
		if(flag==true)
			//.setText("Success. Connected");
			System.out.println("connected");
		else
			System.err.println("not connected");
			//connStatusField.setText("Failure");
	}
    
    private void proceedButtonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	conNameField.setEditable(false);
    	conTypeField.setEditable(false);
    	hostField.setEditable(false);
    	portField.setEditable(false);
    	serviceNameField.setEditable(false);
    	usernameField.setEditable(false);
    	passwordField.setEditable(false);
    	try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			String url = "jdbc:oracle:thin:@" + host + ":" + port + ":"
					+ serviceName;
			Connection con = DriverManager.getConnection(url, user, pass);
			Statement st = con.createStatement();
			guest = new GuestProceed(con,st);
	    	guest.setVisible(true);
			clubLoginInterface = new LoginInterface(con,st);
	    	clubLoginInterface.setVisible(true);
	    	
//	    	String sql = "select clubid, clubname from club where countryid=(select countryid from country where countryname='England')";
//			ResultSet rs = st.executeQuery(sql);
//			while (rs.next()) {				
//				System.out.println(rs.getInt(1) + " " + rs.getString(2));
//			}
			
	    	System.out.println("still connected");
		} catch (ClassNotFoundException | SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel buetLabel;
    private javax.swing.JLabel buetLogo;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField conNameField;
    private javax.swing.JLabel conNameLabel;
    private javax.swing.JTextArea conStatusArea;
    private javax.swing.JTextField conTypeField;
    private javax.swing.JLabel conTypeLabel;
    private javax.swing.JTextField hostField;
    public String host;
    private javax.swing.JLabel hostNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passwordField;
    public String pass;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField portField;
    public String port;
    private javax.swing.JLabel portLabel;
    private javax.swing.JButton proceedButton;
    private javax.swing.JLabel projNameLabel;
    private javax.swing.JLabel serverSideLabel;
    private javax.swing.JTextField serviceNameField;
    public String serviceName;
    private javax.swing.JLabel serviceNameLabel;
    private javax.swing.JButton testConnButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField usernameField;
    public String user;
    public LoginInterface clubLoginInterface;
    public GuestProceed guest;
    // End of variables declaration                   
}
